import type { Metadata } from "next";
import { Roboto, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto"

})

const nunito = Nunito_Sans({
  subsets: ["latin",],
  style: ["italic", "normal"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  variable: "--font-nunito"

})

export const metadata: Metadata = {
  title: "ILanding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${nunito.variable}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
